### ISSUE TITLE
Unable to access gkeep notes via nvim after removing linked device on google account

### ISSUE THREAD

**Issue by bhanu151** [stevearc/gkeep.nvim#10]
**Describe the bug**
I removed the linked device from my google account for security reasons. Later when I tried to access my gkeep notes, I saw the message "Log in with GkeepLogin". When I tried the same, it says that I'm already logged in, but my notes aren't listed. Checkhealth shows that I'm "not logged in but auth token exists".

**To Reproduce**
1. Remove the linked device on your google account
2. Run command ':GkeepEnter'. I see Home, Archive and Trash listed, but none of my existing notes are listed. I see a message next to Home which says 'Log in with GkeepLogin'.
3. Run command ':GkeepLogin'. Output : 'Gkeep logged in ********@gmail.com', i.e, my email address.
4. Run command ':GkeepOpen'. Output : No response seen. The content on the screen does not change.
5. Run command ':GkeepRefresh'. Output : 'Cannot perform action while Gkeep is Uninitialized'

**Expected behavior**
It should ask me for my password or app password to re-login.

**Version information**
 - OS: [e.g. linux, mac, windows]
 Ubuntu 20.04 

 - Neovim: [output of `nvim -v`]
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-wE2acI/neovim-0.7.0~ubuntu1+git202203171546-d238b8f60-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-wE2acI/neovim-0.7.0~ubuntu1+git202203171546-d238b8f60-dd05b3569/build/config -I/build/neovim-wE2acI/neovim-0.7.0~ubuntu1+git202203171546-d238b8f60-dd05b3569/src -I/build/neovim-wE2acI/neovim-0.7.0~ubuntu1+git202203171546-d238b8f60-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-wE2acI/neovim-0.7.0~ubuntu1+git202203171546-d238b8f60-dd05b3569/build/src/nvim/auto -I/build/neovim-wE2acI/neovim-0.7.0~ubuntu1+git202203171546-d238b8f60-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-051

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

 - Gkeep: [output of `:checkhealth gkeep`]
 
 gkeep: health#gkeep#check
========================================================================
## gkeep
  - OK: gkeepapi 0.13.7 installed
  - OK: keyring installed
  - WARNING: Not logged in but auth token exists
    - ADVICE:
      - Try :GkeepOpen
  - INFO: Syncing notes to /home/bhanu/work/notes
  - INFO: Log file: /home/bhanu/.cache/nvim/gkeep.log

**Additional context**

**Screenshots**

**Comment by stevearc** [comment]
Thanks for the report! I've added some handling for this case so that now it should correctly re-prompt you for a password, as well as notify you that the token login failed.

**Comment by bhanu151** [comment]
Thanks for the fix! I'm able to re-login.
