### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by bhanu151** [stevearc/gkeep.nvim#11]
**Describe the bug**
I removed my app-password in my google account and logged out of the device due to some security reasons. Later changed my google password. When I tried to re-open gkeep notes, it asked to login using  `:GkeepLogin`. It asked me for the app password. I entered a new one that I generated. It said 'Complete login flow in browser, then re-attempt GkeepLogin'. It launched a browser session which asks me to login to my google account, in case not already logged in. And nothing else happens in the neovim window

**To Reproduce**
1. Remove app password and logout of device.
2. Change your google account password
3. Open you gkeep notes in neovim. 
4. Try `:GkeepLogin`

**Expected behavior**
It should open my notes.

**Version information**
 - OS: [e.g. linux, mac, windows]
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)" 

 - Neovim: [output of `nvim -v`]
 VIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

 - Gkeep: [output of `:checkhealth gkeep`]

## gkeep
  - OK: gkeepapi 0.13.7 installed
  - OK: keyring installed
  - WARNING: Not logged in
    - ADVICE:
      - Try :GkeepLogin
  - INFO: Syncing notes to /home/bhanu/work/gkeep
  - INFO: Log file: /home/bhanu/.cache/nvim/gkeep.log

**Comment by bhanu151** [comment]
> So after you complete the browser login and re-run `:GkeepLogin`, what happens? Does it spit out an error? Does it put you back into the browser?

It opens up a new blank tab in the browser, since I'm already logged into google now. Each time I run `:GkeepLogin` after having logged into the browser, a fresh blank tab opens up.

**Comment by stevearc** [comment]
Well damn, it looks like Google changed something https://github.com/kiwiz/gkeepapi/issues/123

Logging in is off the menu until that gets resolved 🙁

**Comment by bhanu151** [comment]
Thanks! Will wait for https://github.com/kiwiz/gkeepapi/issues/123 to get resolved.

**Comment by prdanelli** [comment]
To add to this thread. I'm also having issues logging in. I'm able to enter an email and password, the auth request comes through on my 2FA, but the redirect back to the browser just spins. 

When I try and use a different email address, I run the logout method and see the following error: 

```
Error detected while processing function remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
Error invoking '/Users/paul/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep:com
mand:GkeepLogout' on channel 3 (python3-rplugin-host):
error caught in request handler '/Users/paul/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/
python3/gkeep:command:GkeepLogout []':
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/backends/macOS/__init__.py", line 64, in delete
_password
    return api.delete_generic_password(self.keychain, service, username)
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/backends/macOS/api.py", line 172, in delete_gen
eric_password
    Error.raise_for_status(status)
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/backends/macOS/api.py", line 105, in raise_for_
status
    raise NotFound(status, "Item not found")
keyring.backends.macOS.api.NotFound: (-25300, 'Item not found')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paul/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py",
 line 80, in w
    f(self, *args, **kwargs)
  File "/Users/paul/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py",
 line 47, in d
    return f(self, *args)
  File "/Users/paul/.local/share/nvim/site/pack/packer/start/gkeep.nvim/rplugin/python3/gkeep/plugin.py",
 line 615, in cmd_logout
    keyring.delete_password("google-keep-token", email)
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/core.py", line 65, in delete_password
    get_keyring().delete_password(service_name, username)
  File "/opt/homebrew/lib/python3.9/site-packages/keyring/backends/macOS/__init__.py", line 66, in delete
_password
    raise PasswordDeleteError(
keyring.errors.PasswordDeleteError: Can't delete password in keychain: (-25300, 'Item not found')
```

When I remove the plugin, I come back and still cannot enter a new email or complete the login.

**Comment by stevearc** [comment]
Some people over on the linked gkeepapi issue are reporting that upgrading `gpsoauth` has fixed the issue for them. Can you try doing a `pip install --upgrade gpsoauth` inside of your neovim virtualenv (or globally, if you're not using a virtualenv)? I added the gpsoauth version to the output of `:checkhealth gkeep` so you can confirm which version you're using.

**Comment by bhanu151** [comment]
Thanks Steven! The login is working fine after `gpsoauth` upgrade.
