### ISSUE TITLE
Uninstalled plugin but keep getting an error on opening vim

### ISSUE THREAD

**Issue by dbatten5** [stevearc/gkeep.nvim#14]
**Describe the bug**
I removed this plugin using `PlugClean` but now when I enter (neo)vim I get the following error:

```
Error detected while processing BufEnter Autocommands for "*"..function remote#define#AutocmdBootstrap[7]..BufEnter Autocommands for "*"..function remote#define#request:
line    2:
Error invoking '/Users/xxx/.local/share/nvim/plugged/gkeep.nvim/rplugin/python3/gkeep:autocmd:BufEnter:*' on channel 3 (python3-rplugin-host):
no request handler registered for "/Users/xxx/.local/share/nvim/plugged/gkeep.nvim/rplugin/python3/gkeep:autocmd:BufEnter:*"
```

I've no idea where this is coming from or how I can stop it coming up. I've tried clearing autocommands with `:autocmd!` but no luck. I can see this process keeps getting spawned even after I kill it

```
ps aux | grep gkeep
xxx     1884   0.0  0.1  4261132  12420   ??  Ss    8:50pm   0:00.13 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python -c import sys; sys.path = [p for p in sys.path if p != ""]; import neovim; neovim.start_host() /Users/xxx/.local/share/nvim/plugged/gkeep.nvim/rplugin/python3/gkeep
```

I've also tried restarting iTerm2 and my laptop but no progress. Is there some `pynvim` cache I need to clear somewhere? I'm all out of ideas, any help welcome. Thanks

**Version information**
 - OS: mac
 - Neovim: NVIM v0.8.0

**Comment by stevearc** [comment]
Run `:UpdateRemotePlugins`

**Comment by dbatten5** [comment]
That's it! Thanks for your quick reply
