### ISSUE TITLE
typing_extensions

### ISSUE THREAD

**Issue by adamcoatess** [stevearc/gkeep.nvim#18]
**Describe the bug**
Running :UpdateRemotePlugins, there is an error that the python package typing_extensions is not recognised. Therefore to fix this I had to manually pip install typing_extensions before using this plugin. 

**To Reproduce**
If typing_extensions is not already installed, then :UpdateRemotePlugins won't work. 

**Expected behavior**
Perhaps there's an issue with the install of the requirements for python packages within the script. I'm not sure exactly where but perhaps they need to be updated? 

**Version information**
 - OS: linux
 - Neovim: 0.9.5
 - Gkeep: (all okay after pip install "typing_extensions")

EDIT: For more information the plugin worked fine prior to the commit `5d20831` , therefore an additional python package I had to install prior to the plugin working. And this is just an FYI, the problem is already resolved for me after pip installing typing_extensions.

**Comment by stevearc** [comment]
Thanks for the report! Previously we only used typing_extensions for python 3.8, but in that commit I started using `assert_never`, which is _only_ available in typing_extensions in all versions of python. I updated the auto-install logic to install typing_extensions for all python versions.

**Comment by adamcoatess** [comment]
Perfect thanks! That makes sense now since I use Python 3.11.6 which needs the addtitional typing_extensions to be able to use `assert_never` .  But now the updated auto_install looks like it addresses this now. 

Thanks very much! (great plugin!)
