### ISSUE TITLE
setup function is nil

### ISSUE THREAD

**Issue by tanj** [stevearc/gkeep.nvim#19]
**Describe the bug**

**To Reproduce**
1. Add gkeep.nvim example lazy config to nvim 0.10
2. Start nvim and sync/update lazy
3. Restart nvim

receive message:
```
Failed to run `config` for gkeep.nvim
 .../Local/nvim-data/lazy/lazy.nvim/lua/lazy/core/loader.lua:373: attempt to call field 'setup' (a nil value) 
 # stacktrace: - init.lua:260
```

**Expected behavior**
gkeep would load without error

**Version information**
 - OS: [e.g. linux, mac, windows]
     - Windows 11 Pro
 - Neovim: [output of `nvim -v`]
     - NVIM v0.10.0-dev-2826+gf6dcc464f
 - Gkeep: [output of `:checkhealth gkeep`]
```
gkeep: health#gkeep#check

gkeep ~
- OK gkeepapi 0.15.1 installed
- OK gpsoauth 1.0.4 installed
- OK urllib3 1.26.18 installed
- OK keyring installed
- ERROR Remote plugin not found
  - ADVICE:
    - Try running :UpdateRemotePlugins and restart
```

**Additional context**
I'm not sure if this is related to the lack of setup, but I don't get any plugins listed in the `rplugin.vim` after running `UpdateRemotePlugins`

**Comment by stevearc** [comment]
You are probably using lazy.nvim and have set `config = true` or `opts = {}`. Either of those values causes lazy to call `require("gkeep").setup()`, but setup is not a function that exists as all configuration is done by other means in this plugin.

**Comment by tanj** [comment]
ya, that was it. 😞 

Sorry about the erroneous bug report.
