### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by WBuddhi** [stevearc/gkeep.nvim#3]
**Describe the bug**
When running the `GkeepLogin` command, I pass in the email address and password, all authentication processes are taken place, but then nothing happens. Webpage shows `One moment please` but never goes past that

**To Reproduce**
1. Go to nvim
2. Run command 'GkeepLogin'
![2021-11-28-181127_1920x1080_scrot](https://user-images.githubusercontent.com/5512438/143778707-d83f25e4-5e2c-4260-911a-5ff00b5b5abd.png)

4. See error: None

**Expected behavior**

Login to gkeep and see gkeep notes

**Version information**
 - arch linux
 - Neovim: v0.5.1
 - Gkeep: 0.13.6
 
**Additional context**

**Screenshots**

**Comment by stevearc** [comment]
This sounds like a google auth problem; I'm not sure if there's anything we can do about it from the gkeep side. From searching around, you can try [clearing your browser cookies](https://stackoverflow.com/questions/63352633/google-sign-in-blank-page-one-moment-please) or [marking the urls as trusted](https://www.itechtics.com/fix-google-drive-stuck-at-one-moment-please/). You could also try using a different browser, or you could try opening the devtools to see if there are any errors that contain clues. If you have 2-factor enabled, you could try temporarily disabling it, or you could try enabling it if you're not using it.

**Comment by kaizerx31** [comment]
I am facing the same issue

**Comment by WBuddhi** [comment]
I found the solution for this, follow [this](https://github.com/kiwiz/gkeepapi/issues/81)

**Comment by kaizerx31** [comment]
Thanks it works now

**Comment by stevearc** [comment]
Glad to hear it! I'm going to close this and pin it so it's easy to find if others encounter the same problem.

**Comment by srbhp** [comment]
I get this error 

> Unknown error logging in; please report an issue on github. API error: ('BadAuthentication', None)


But this Python script worked for me 

```
import gkeepapi

keep = gkeepapi.Keep()
success = keep.login('userid@gmail.com', 'APP-Passward')
print("######    TO DO             ################################")
gnotes = keep.all()
for ig in gnotes:
    if ig.pinned:
        print(ig.title)
        print(ig.text)
print("############################################################")


`:checkhealth gkeep`
Gives me 

`## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3.9"
  - INFO: Executable: /usr/bin/python3.9
  - INFO: Python version: 3.9.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
`

I suspect gkeep.nvim somehow picks up an older version of python. 
How do I debug it ?

**Comment by stevearc** [comment]
This is unrelated to the original issue, so I have filed a new one for you and moved the discussion over there

**Comment by kaddkaka** [comment]
Even though I use an App Password that I just generated I get this error when trying `:GkeepLogin`:
`Failed to log in: incorrect password`

What do I do?

**Comment by stevearc** [comment]
@kaddkaka please file a new issue using the bug report template. This is unrelated to the original report here.
